In [41]:

import numpy as np
arr=np.array([1,2,3])
print(arr)


[1 2 3]


In [13]:
//create 2d array with 6 rows and 5 coloumb
import numpy as np
arr=np.arange(30).reshape(6,5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [27]:
import numpy as np
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [29]:
import numpy as np
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [39]:

import numpy as np
np.full((2,4),7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7]])

In [47]:
import numpy as np

arr = np.arange(49).reshape(7,7)
#Prt 1
print(arr[:,:])
#Prt 2
print(arr[2:5, 0:3])
#Prt 3
print(arr[0:2, 0:5])
#Prt 4
print(arr[2:4, 2:4])
#Prt 5
print(arr[-3:-1, -3:-1])
#Prt 6
print(arr[-4:-1, -4:-1])

SyntaxError: invalid non-printable character U+00A0 (1953769328.py, line 15)

In [49]:
import numpy as np

arr = np.array([1, 2, 3, 4])
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr.ndim)
print(arr1.ndim)
print(arr2.ndim)

1
2
3


In [53]:
#Question 7
#Create 8D Array with value [2, 2, 2, 2]
import numpy as np

arr = np.array([2, 2, 2, 2], ndmin = 8)
print(arr)

[[[[[[[[2 2 2 2]]]]]]]]
